# Generated by Django 3.0.2 on 2020-03-04 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_auto_20200304_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='place',
        ),
    ]
