# Generated by Django 3.0.2 on 2020-03-05 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_remove_user_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_1',
            old_name='image',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order_1',
            old_name='buyproduct',
            new_name='card_number',
        ),
        migrations.RenameField(
            model_name='order_1',
            old_name='pname',
            new_name='fullname',
        ),
        migrations.RenameField(
            model_name='order_1',
            old_name='status',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='order_1',
            old_name='total_amount',
            new_name='item_price',
        ),
        migrations.RenameField(
            model_name='order_1',
            old_name='username',
            new_name='item_type',
        ),
        migrations.AddField(
            model_name='order_1',
            name='item_image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='order_1',
            name='paid_by',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order_1',
            name='userid',
            field=models.IntegerField(null=True),
        ),
    ]
