# Generated by Django 3.0.2 on 2020-03-10 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_contact_message_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photos', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
