# Generated by Django 3.0.2 on 2020-02-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shopid', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=100, null=True)),
                ('highlights', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('photo', models.TextField(null=True)),
                ('actual_price', models.CharField(max_length=100, null=True)),
                ('offer_price', models.CharField(max_length=100, null=True)),
                ('termsandconditions', models.TextField(null=True)),
                ('validity', models.CharField(max_length=100, null=True)),
                ('couponcount', models.CharField(max_length=100, null=True)),
                ('place', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ordernumber', models.CharField(max_length=100, null=True)),
                ('offerid', models.IntegerField(null=True)),
                ('userid', models.IntegerField(null=True)),
                ('shopid', models.IntegerField(null=True)),
                ('price', models.IntegerField(null=True)),
                ('address', models.TextField(null=True)),
                ('couponcode', models.CharField(max_length=100, null=True)),
                ('timestamp', models.CharField(max_length=100, null=True)),
                ('active', models.IntegerField(null=True)),
                ('redeem_time', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('offerid', models.IntegerField(null=True)),
                ('userid', models.IntegerField(null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('about', models.TextField(null=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('address', models.TextField(null=True)),
                ('latitude', models.CharField(max_length=100, null=True)),
                ('longitude', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=25, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
                ('place', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
    ]
