# Generated by Django 2.2.13 on 2020-07-01 21:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20200309_0815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 2, 2, 36, 13, 52209)),
        ),
    ]
