# Generated by Django 4.0.4 on 2022-06-02 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_coupons_couponscodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='discount_percentage',
            field=models.FloatField(default=0),
        ),
    ]
