# Generated by Django 2.2.13 on 2020-07-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_auto_20200702_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='active',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
