# Generated by Django 4.0.4 on 2022-06-02 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_coupons_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='append_text',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
