# Generated by Django 2.2.13 on 2020-07-02 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20200702_0308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='offerid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='shopid',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='userid',
        ),
        migrations.AddField(
            model_name='orders',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Offer'),
        ),
        migrations.AddField(
            model_name='orders',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Shop'),
        ),
        migrations.AddField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.User'),
        ),
    ]
