# Generated by Django 4.0.4 on 2022-06-02 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_coupons_append_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.shop'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='couponscodes',
            name='shop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='frontend.shop'),
            preserve_default=False,
        ),
    ]
