# Generated by Django 4.0.4 on 2022-06-02 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_coupons_shop_couponscodes_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupons',
            name='discount_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
