# Generated by Django 2.2.13 on 2020-07-13 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_offer_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField()),
                ('review', models.TextField(null=True)),
                ('Offer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.Offer')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='frontend.User')),
            ],
        ),
    ]
