# Generated by Django 4.0.4 on 2022-06-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_alter_coupons_discount_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponscodes',
            name='coupon_code',
            field=models.CharField(max_length=200),
        ),
    ]
