# Generated by Django 2.2.13 on 2020-07-13 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0013_auto_20200713_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photos', models.CharField(max_length=255, null=True)),
                ('text', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
