# Generated by Django 3.0.2 on 2020-02-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=255, null=True)),
                ('date', models.CharField(max_length=255, null=True)),
                ('time', models.CharField(max_length=25, null=True)),
                ('contact', models.CharField(max_length=255, null=True)),
                ('amount', models.CharField(max_length=15, null=True)),
                ('image', models.TextField(null=True)),
                ('seat', models.CharField(max_length=255, null=True)),
                ('event', models.CharField(max_length=255, null=True)),
                ('more', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itemadd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('available', models.CharField(max_length=255, null=True)),
                ('amount', models.CharField(max_length=25, null=True)),
                ('image', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('lang', models.CharField(max_length=255, null=True)),
                ('image', models.TextField(null=True)),
                ('audio', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mysq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.TextField(null=True)),
                ('username', models.CharField(max_length=255, null=True)),
                ('dob', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('nationality', models.CharField(max_length=255, null=True)),
                ('mobno', models.CharField(max_length=255, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_1',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, null=True)),
                ('image', models.TextField(null=True)),
                ('pname', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('buyproduct', models.CharField(max_length=255, null=True)),
                ('total_amount', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('item', models.CharField(max_length=255, null=True)),
                ('quantity', models.CharField(max_length=255, null=True)),
                ('amount', models.CharField(max_length=255, null=True)),
                ('date', models.CharField(max_length=255, null=True)),
                ('total', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('photos', models.CharField(max_length=255, null=True)),
                ('user_id', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=25, null=True)),
                ('password', models.CharField(max_length=255, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
                ('place', models.CharField(max_length=255, null=True)),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_history',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('login_id', models.IntegerField(null=True)),
                ('usage_track', models.TextField(null=True)),
                ('usage_status', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
