# Generated by Django 3.0.2 on 2020-03-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_contact_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_message',
            name='email',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
