# Generated by Django 3.0.2 on 2020-03-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='text',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
